# Generated by Django 5.1.4 on 2024-12-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings_All",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовок")),
                ("static", models.IntegerField(verbose_name="Статистика")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "Статистика в Главном Странице",
            },
        ),
    ]
