# Generated by Django 5.1.4 on 2025-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contact_index_steps_delete_settings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TimeField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'faq',
            },
        ),
    ]
